# -*- coding: utf-8 -*-
"""Mini LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsL7TgdONcEXmXw9EwB0-9vl45Fq2fxW
"""

!pip install wikipedia

import tensorflow as tf
from tensorflow.keras.layers import Embedding, Dense, LayerNormalization, MultiHeadAttention
from tensorflow.keras.models import Model
import numpy as np
import faiss

import wikipedia

topics = [
    "Artificial intelligence",
    "Machine learning",
    "Transformer (deep learning)",
    "Retrieval-augmented generation"
]

wiki_data = {}

for topic in topics:
    try:
        wiki_data[topic] = wikipedia.page(topic, auto_suggest=False).content
    except Exception as e:
        print(f" Skipped {topic}: {e}")

merged_text = "\n\n".join(wiki_data.values())

print(" Data collected:", list(wiki_data.keys()))
print(" Total chars:", len(merged_text))

"""Let's scrap some data from wikipedia post"""

print(merged_text[:2000])  # preview

size= len(merged_text)
print(size)

from tokenizers import ByteLevelBPETokenizer

tokenizer = ByteLevelBPETokenizer()
tokenizer.train_from_iterator([merged_text], vocab_size=5000, min_frequency=2)

encoded = tokenizer.encode(merged_text)

print(" Tokens:", encoded.tokens[:10])
print("IDs:", encoded.ids[:10])

import numpy as np
from sklearn.model_selection import train_test_split

# Config
seq_len  = 20
embed_dim, heads, ff_dim, max_len = 128, 4, 256, 100
vocab_size = tokenizer.get_vocab_size()  # from BPE tokenizer

# Sequences
ids = np.array(encoded.ids)
X = np.array([ids[i:i+seq_len]   for i in range(len(ids) - seq_len)])
Y = np.array([ids[i+1:i+seq_len+1] for i in range(len(ids) - seq_len)])

# Split
X_train, X_valid, Y_train, Y_valid = train_test_split(X, Y, test_size=0.2, shuffle=True)

print(f" Train: {X_train.shape} | Valid: {X_valid.shape} | Vocab: {vocab_size}")

@tf.keras.utils.register_keras_serializable()
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embed_dim, max_len):
        super().__init__()
        self.token_emb = Embedding(vocab_size, embed_dim)
        self.pos_emb   = Embedding(max_len, embed_dim)

    def call(self, x):
        positions = tf.range(tf.shape(x)[1])
        return self.token_emb(x) + self.pos_emb(positions)

class GPTBlock(tf.keras.layers.Layer):
    def __init__(self, embed_dim, heads, ff_dim):
        super().__init__()
        self.att  = MultiHeadAttention(num_heads=heads, key_dim=embed_dim)
        self.ffn  = tf.keras.Sequential([Dense(ff_dim, activation="relu"), Dense(embed_dim)])
        self.norm1 = LayerNormalization()
        self.norm2 = LayerNormalization()

    def call(self, x):
        attn = self.att(x, x, use_causal_mask=True)
        x = self.norm1(x + attn)
        return self.norm2(x + self.ffn(x))

# --------------------------
# GPT Model
# --------------------------

inputs = tf.keras.Input(shape=(seq_len,))

x = PositionalEmbedding(vocab_size, embed_dim, max_len)(inputs)

x = GPTBlock(embed_dim, heads, ff_dim)(x)
x = GPTBlock(embed_dim, heads, ff_dim)(x)

outputs = Dense(vocab_size, activation="softmax")(x)

model = tf.keras.Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.0003),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# --------------------------
# Train
# --------------------------
model.fit(
    X_train,
    Y_train,
    validation_data=(X_valid, Y_valid),
    epochs=20,
    batch_size=32
)

!pip install semantic-text-splitter -q

from semantic_text_splitter import TextSplitter

splitter = TextSplitter(1000)

chunks = [
    {"text": chunk, "source": topic}
    for topic, text in wiki_data.items()
    for chunk in splitter.chunks(text)
]

print("✅ Total chunks:", len(chunks))

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# embedding model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# convert text → vectors
doc_embeddings = embedder.encode([c["text"] for c in chunks])

# FAISS index
dim = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(np.array(doc_embeddings))

def retrieve(query, k=2):
    q_emb = embedder.encode([query])

    distances, indices = index.search(q_emb, k)

    return [chunks[i] for i in indices[0]]

def generate_with_rag(query):

    #  retrieve relevant context
    context_chunks = retrieve(query, k=2)

    context_text = " ".join([c["text"] for c in context_chunks])

    # build prompt
    prompt = context_text + " " + query

    #  limit length (important for your small model)
    prompt_words = prompt.split()[-20:]   # keep last tokens
    prompt = " ".join(prompt_words)

    #  generate using model
    return generate(prompt)

def generate(seed, steps=200, temperature=0.3):
    ids = tokenizer.encode(seed).ids

    for _ in range(steps):
        seq = ids[-seq_len:]

        if len(seq) < seq_len:
            seq = [0] * (seq_len - len(seq)) + seq

        seq = np.array(seq).reshape(1, seq_len)

        pred = model.predict(seq, verbose=0)
        probs = pred[0, -1]

        probs = np.log(probs + 1e-9) / temperature
        probs = np.exp(probs)
        probs = probs / np.sum(probs)

        next_id = np.random.choice(len(probs), p=probs)
        ids.append(next_id)

    return tokenizer.decode(ids)

print(generate_with_rag("What is Transformer?"))

import os
os.makedirs("artifacts", exist_ok=True)

# save model
model.save_weights("artifacts/model_weights.weights.h5")

# save tokenizer (replaces vocab.json)
tokenizer.save("artifacts/tokenizer.json")

print("All artifacts saved")

tokenizer.save("tokenizer.json")
model.save_weights("model.weights.h5")

import shutil
shutil.make_archive("artifacts", "zip", "artifacts")

from google.colab import files
files.download("artifacts.zip")

import os, json, faiss, shutil
from google.colab import files

model.save("artifacts/model.keras")
faiss.write_index(index, "artifacts/faiss.index")
with open("artifacts/chunks.json", "w") as f:
    json.dump(chunks, f)

print(os.listdir("artifacts"))

shutil.make_archive("artifacts", "zip", "artifacts")
files.download("artifacts.zip")

